// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: code.proto

package server

import (
	"context"

	"github.com/ac-dcz/lightRW/apps/code/rpc/internal/logic"
	"github.com/ac-dcz/lightRW/apps/code/rpc/internal/svc"
	"github.com/ac-dcz/lightRW/apps/code/rpc/pb"
)

type VerifyCodeServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedVerifyCodeServer
}

func NewVerifyCodeServer(svcCtx *svc.ServiceContext) *VerifyCodeServer {
	return &VerifyCodeServer{
		svcCtx: svcCtx,
	}
}

func (s *VerifyCodeServer) GenCode(ctx context.Context, in *pb.GenCodeReq) (*pb.GenCodeResp, error) {
	l := logic.NewGenCodeLogic(ctx, s.svcCtx)
	return l.GenCode(in)
}

func (s *VerifyCodeServer) VerifyCode(ctx context.Context, in *pb.VerifyCodeReq) (*pb.VerifyCodeResp, error) {
	l := logic.NewVerifyCodeLogic(ctx, s.svcCtx)
	return l.VerifyCode(in)
}
