// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.1
// source: store.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Store_RegistryStore_FullMethodName = "/pb.Store/RegistryStore"
	Store_GetStoreInfo_FullMethodName  = "/pb.Store/GetStoreInfo"
	Store_AddGoods_FullMethodName      = "/pb.Store/AddGoods"
	Store_GetGoodsStock_FullMethodName = "/pb.Store/GetGoodsStock"
)

// StoreClient is the client API for Store service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoreClient interface {
	RegistryStore(ctx context.Context, in *RegistryStoreReq, opts ...grpc.CallOption) (*RegistryStoreResp, error)
	GetStoreInfo(ctx context.Context, in *StoreInfoReq, opts ...grpc.CallOption) (*StoreInfoResp, error)
	AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error)
	GetGoodsStock(ctx context.Context, in *GoodsStockReq, opts ...grpc.CallOption) (*GoodsStockResp, error)
}

type storeClient struct {
	cc grpc.ClientConnInterface
}

func NewStoreClient(cc grpc.ClientConnInterface) StoreClient {
	return &storeClient{cc}
}

func (c *storeClient) RegistryStore(ctx context.Context, in *RegistryStoreReq, opts ...grpc.CallOption) (*RegistryStoreResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistryStoreResp)
	err := c.cc.Invoke(ctx, Store_RegistryStore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetStoreInfo(ctx context.Context, in *StoreInfoReq, opts ...grpc.CallOption) (*StoreInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreInfoResp)
	err := c.cc.Invoke(ctx, Store_GetStoreInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) AddGoods(ctx context.Context, in *AddGoodsReq, opts ...grpc.CallOption) (*AddGoodsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGoodsResp)
	err := c.cc.Invoke(ctx, Store_AddGoods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeClient) GetGoodsStock(ctx context.Context, in *GoodsStockReq, opts ...grpc.CallOption) (*GoodsStockResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GoodsStockResp)
	err := c.cc.Invoke(ctx, Store_GetGoodsStock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreServer is the server API for Store service.
// All implementations must embed UnimplementedStoreServer
// for forward compatibility.
type StoreServer interface {
	RegistryStore(context.Context, *RegistryStoreReq) (*RegistryStoreResp, error)
	GetStoreInfo(context.Context, *StoreInfoReq) (*StoreInfoResp, error)
	AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error)
	GetGoodsStock(context.Context, *GoodsStockReq) (*GoodsStockResp, error)
	mustEmbedUnimplementedStoreServer()
}

// UnimplementedStoreServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoreServer struct{}

func (UnimplementedStoreServer) RegistryStore(context.Context, *RegistryStoreReq) (*RegistryStoreResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegistryStore not implemented")
}
func (UnimplementedStoreServer) GetStoreInfo(context.Context, *StoreInfoReq) (*StoreInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStoreInfo not implemented")
}
func (UnimplementedStoreServer) AddGoods(context.Context, *AddGoodsReq) (*AddGoodsResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddGoods not implemented")
}
func (UnimplementedStoreServer) GetGoodsStock(context.Context, *GoodsStockReq) (*GoodsStockResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoodsStock not implemented")
}
func (UnimplementedStoreServer) mustEmbedUnimplementedStoreServer() {}
func (UnimplementedStoreServer) testEmbeddedByValue()               {}

// UnsafeStoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoreServer will
// result in compilation errors.
type UnsafeStoreServer interface {
	mustEmbedUnimplementedStoreServer()
}

func RegisterStoreServer(s grpc.ServiceRegistrar, srv StoreServer) {
	// If the following call pancis, it indicates UnimplementedStoreServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Store_ServiceDesc, srv)
}

func _Store_RegistryStore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistryStoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).RegistryStore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_RegistryStore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).RegistryStore(ctx, req.(*RegistryStoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetStoreInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetStoreInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_GetStoreInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetStoreInfo(ctx, req.(*StoreInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_AddGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGoodsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).AddGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_AddGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).AddGoods(ctx, req.(*AddGoodsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Store_GetGoodsStock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodsStockReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreServer).GetGoodsStock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Store_GetGoodsStock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreServer).GetGoodsStock(ctx, req.(*GoodsStockReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Store_ServiceDesc is the grpc.ServiceDesc for Store service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Store_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Store",
	HandlerType: (*StoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistryStore",
			Handler:    _Store_RegistryStore_Handler,
		},
		{
			MethodName: "GetStoreInfo",
			Handler:    _Store_GetStoreInfo_Handler,
		},
		{
			MethodName: "AddGoods",
			Handler:    _Store_AddGoods_Handler,
		},
		{
			MethodName: "GetGoodsStock",
			Handler:    _Store_GetGoodsStock_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "store.proto",
}
