// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type Goods struct {
	GoodsId uint64 `json:"goods_id"`
	Sku     string `json:"sku"`
	Name    string `json:"name"`
}

type GoodsInfoReq struct {
	Sku string `path:"sku"`
}

type GoodsInfoResp struct {
	Goods
}

type RegistryGoodsReq struct {
	Sku  string `form:"sku"`
	Name string `form:"name"`
}

type RegistryGoodsResp struct {
	Goods
}
