// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/ac-dcz/lightRW/apps/order/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/create",
					Handler: CreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/info",
					Handler: OrderInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/pay",
					Handler: PayOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/order"),
	)
}
