// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: goods.proto

package server

import (
	"context"

	"github.com/ac-dcz/lightRW/apps/goods/rpc/internal/logic"
	"github.com/ac-dcz/lightRW/apps/goods/rpc/internal/svc"
	"github.com/ac-dcz/lightRW/apps/goods/rpc/pb"
)

type GoodsRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGoodsRpcServer
}

func NewGoodsRpcServer(svcCtx *svc.ServiceContext) *GoodsRpcServer {
	return &GoodsRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsRpcServer) RegistryGoods(ctx context.Context, in *pb.RegistryGoodsReq) (*pb.RegistryGoodsResp, error) {
	l := logic.NewRegistryGoodsLogic(ctx, s.svcCtx)
	return l.RegistryGoods(in)
}

func (s *GoodsRpcServer) GoodsInfo(ctx context.Context, in *pb.GoodsInfoReq) (*pb.GoodsInfoResp, error) {
	l := logic.NewGoodsInfoLogic(ctx, s.svcCtx)
	return l.GoodsInfo(in)
}
