// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type SignInReq struct {
	Tel  string `json:"tel" validate:"required"`
	Pass string `json:"pass" validate:"required"`
	Code string `json:"code"`
}

type SignInResp struct {
	User
	Token string `json:"token"`
}

type SignUpReq struct {
	Tel      string `json:"tel" validate:"required"`
	Code     string `json:"code" validate:"required"`
	NickName string `json:"nick_name" validate:"required"`
	Pass     string `json:"pass" validate:"required"`
	Level    uint32 `json:"level" validate:"required"`
}

type SignUpResp struct {
	User
}

type User struct {
	NickName string `json:"nick_name" validate:"required"`
	Tel      string `json:"tel" validate:"required"`
	Level    uint32 `json:"level" validate:"required"`
	Uid      uint64 `json:"uid" validate:"required"`
}
