// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: genid.proto

package genid

import (
	"context"

	"github.com/ac-dcz/lightRW/apps/genid/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetIdReq  = pb.GetIdReq
	GetIdResp = pb.GetIdResp

	GenId interface {
		GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error)
	}

	defaultGenId struct {
		cli zrpc.Client
	}
)

func NewGenId(cli zrpc.Client) GenId {
	return &defaultGenId{
		cli: cli,
	}
}

func (m *defaultGenId) GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error) {
	client := pb.NewGenIdClient(m.cli.Conn())
	return client.GetId(ctx, in, opts...)
}
