// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ProposeReviewReq struct {
	OrderId    uint64 `json:"order_id" validate:"required"`
	StoreId    uint64 `json:"store_id" validate:"required"`
	Sku        string `json:"sku" validate:"required"`
	Level      uint8  `json:"level,range=[1,3]" validate:"required"`
	GoodsDesc  string `json:"goodsDesc" validate:"required"`
	HasImage   bool   `json:"has_image"`
	ImageCDN   string `json:"image_cdn"`
	StoreScore uint8  `json:"store_score,range=[1,5]" validate:"required"`
}

type ProposeReviewResp struct {
	ReviewId uint64 `json:"review_id"`
	Status   uint8  `json:"status"`
}

type ReviewByReviewIdReq struct {
	ReviewId uint64 `json:"review_id" validate:"required"`
}

type ReviewByReviewIdResp struct {
	Info ReviewInfo `json:"info"`
}

type ReviewBySSkuReq struct {
	StoreId uint64 `json:"store_id" validate:"required"`
	Sku     string `json:"sku" validate:"required"`
}

type ReviewBySSkuResp struct {
	Infos []ReviewInfo `json:"infos"`
}

type ReviewByUidResp struct {
	Infos []ReviewInfo `json:"infos"`
}

type ReviewInfo struct {
	Uid        uint64 `json:"uid"`
	OrderId    uint64 `json:"order_id"`
	StoreId    uint64 `json:"store_id"`
	Sku        string `json:"sku"`
	Level      uint8  `json:"level,range=[1,3]"`
	GoodDesc   string `json:"good_desc"`
	HasImage   bool   `json:"has_image"`
	ImageCDN   string `json:"image_cdn"`
	StoreScore uint8  `json:"store_score,range=[1,5]"`
	Status     uint8  `json:"status"`
	IsDel      uint8  `json:"is_del"`
	CreateAt   string `json:"create_at"`
	ReviewId   uint64 `json:"review_id"`
}
