// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/ac-dcz/lightRW/apps/enroll/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/signin",
				Handler: SignInHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/signup",
				Handler: SignUpHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/enroll"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/gen",
				Handler: GenVerifyCodeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/code"),
	)
}
