// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/ac-dcz/lightRW/apps/review/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.RateLimit},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/get/reviewid",
					Handler: ReviewByReviewIdHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/get/ssku",
					Handler: ReviewBySSkuHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/get/uid",
					Handler: ReviewByUidHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/propose",
					Handler: ProposeReviewHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/review"),
	)
}
