// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type CreateOrderReq struct {
	Entries []OrderEntry `json:"entries" validate:"required"`
	Token   string       `json:"token,optional"`
}

type CreateOrderResp struct {
	OrderId uint64 `json:"order_id"`
	Status  int32  `json:"status"`
}

type OrderEntry struct {
	StoreId uint64 `json:"store_id" validate:"required`
	Sku     string `json:"sku" validate:"required`
	Nums    int32  `json:"nums" validate:"required`
}

type OrderInfoReq struct {
	OrderId uint64 `json:"order_id" validate:"required`
	Token   string `json:"token,optional"`
}

type OrderInfoResp struct {
	Id       uint64       `json:"id"`
	OrderId  uint64       `json:"order_id"`
	Uid      uint64       `json:"uid"`
	Status   int32        `json:"status"`
	Entries  []OrderEntry `json:"entries"`
	CreateAt string       `json:"create_at"`
}

type PayOrderReq struct {
	OrderId uint64 `json:"order_id" validate:"required`
	Token   string `json:"token,optional"`
}

type PayOrderResp struct {
	Status int32 `json:"status"`
}
