// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.23.1
// source: genid.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GenId_GetId_FullMethodName = "/genid.GenId/GetId"
)

// GenIdClient is the client API for GenId service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GenIdClient interface {
	GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error)
}

type genIdClient struct {
	cc grpc.ClientConnInterface
}

func NewGenIdClient(cc grpc.ClientConnInterface) GenIdClient {
	return &genIdClient{cc}
}

func (c *genIdClient) GetId(ctx context.Context, in *GetIdReq, opts ...grpc.CallOption) (*GetIdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIdResp)
	err := c.cc.Invoke(ctx, GenId_GetId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GenIdServer is the server API for GenId service.
// All implementations must embed UnimplementedGenIdServer
// for forward compatibility.
type GenIdServer interface {
	GetId(context.Context, *GetIdReq) (*GetIdResp, error)
	mustEmbedUnimplementedGenIdServer()
}

// UnimplementedGenIdServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGenIdServer struct{}

func (UnimplementedGenIdServer) GetId(context.Context, *GetIdReq) (*GetIdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetId not implemented")
}
func (UnimplementedGenIdServer) mustEmbedUnimplementedGenIdServer() {}
func (UnimplementedGenIdServer) testEmbeddedByValue()               {}

// UnsafeGenIdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GenIdServer will
// result in compilation errors.
type UnsafeGenIdServer interface {
	mustEmbedUnimplementedGenIdServer()
}

func RegisterGenIdServer(s grpc.ServiceRegistrar, srv GenIdServer) {
	// If the following call pancis, it indicates UnimplementedGenIdServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GenId_ServiceDesc, srv)
}

func _GenId_GetId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GenIdServer).GetId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GenId_GetId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GenIdServer).GetId(ctx, req.(*GetIdReq))
	}
	return interceptor(ctx, in, info, handler)
}

// GenId_ServiceDesc is the grpc.ServiceDesc for GenId service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GenId_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "genid.GenId",
	HandlerType: (*GenIdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetId",
			Handler:    _GenId_GetId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "genid.proto",
}
