// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.0
// 	protoc        v4.23.1
// source: genid.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdReq) Reset() {
	*x = GetIdReq{}
	mi := &file_genid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdReq) ProtoMessage() {}

func (x *GetIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_genid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdReq.ProtoReflect.Descriptor instead.
func (*GetIdReq) Descriptor() ([]byte, []int) {
	return file_genid_proto_rawDescGZIP(), []int{0}
}

type GetIdResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIdResp) Reset() {
	*x = GetIdResp{}
	mi := &file_genid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdResp) ProtoMessage() {}

func (x *GetIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_genid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdResp.ProtoReflect.Descriptor instead.
func (*GetIdResp) Descriptor() ([]byte, []int) {
	return file_genid_proto_rawDescGZIP(), []int{1}
}

func (x *GetIdResp) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_genid_proto protoreflect.FileDescriptor

var file_genid_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x67, 0x65, 0x6e, 0x69, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x0a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x22, 0x1b, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x64, 0x32, 0x2d, 0x0a, 0x05, 0x47, 0x65,
	0x6e, 0x49, 0x64, 0x12, 0x24, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x49, 0x64, 0x12, 0x0c, 0x2e, 0x70,
	0x62, 0x2e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x70, 0x62, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_genid_proto_rawDescOnce sync.Once
	file_genid_proto_rawDescData = file_genid_proto_rawDesc
)

func file_genid_proto_rawDescGZIP() []byte {
	file_genid_proto_rawDescOnce.Do(func() {
		file_genid_proto_rawDescData = protoimpl.X.CompressGZIP(file_genid_proto_rawDescData)
	})
	return file_genid_proto_rawDescData
}

var file_genid_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_genid_proto_goTypes = []any{
	(*GetIdReq)(nil),  // 0: pb.GetIdReq
	(*GetIdResp)(nil), // 1: pb.GetIdResp
}
var file_genid_proto_depIdxs = []int32{
	0, // 0: pb.GenId.GetId:input_type -> pb.GetIdReq
	1, // 1: pb.GenId.GetId:output_type -> pb.GetIdResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_genid_proto_init() }
func file_genid_proto_init() {
	if File_genid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_genid_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_genid_proto_goTypes,
		DependencyIndexes: file_genid_proto_depIdxs,
		MessageInfos:      file_genid_proto_msgTypes,
	}.Build()
	File_genid_proto = out.File
	file_genid_proto_rawDesc = nil
	file_genid_proto_goTypes = nil
	file_genid_proto_depIdxs = nil
}
