// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type AddGoodsReq struct {
	StoreId uint64 `json:"store_id"`
	Sku     string `json:"sku"`
	Stock   uint64 `json:"stock"`
	Token   string `form:"token,optional"`
}

type GoodsInfo struct {
	Sku   string `json:"sku"`
	Stock uint64 `json:"stock"`
}

type GoodsStockReq struct {
	StoreId uint64 `form:"store_id"`
	Sku     string `form:"sku"`
}

type GoodsStockResp struct {
	Stock uint64 `json:"stock"`
}

type RegistryStoreReq struct {
	Name  string `form:"name"`
	Token string `form:"token,optional"`
}

type RegistryStoreResp struct {
	StoreInfo
}

type StoreInfo struct {
	Id         uint64      `json:"id"`
	StoreId    uint64      `json:"store_id"`
	Name       string      `json:"name"`
	Uid        uint64      `json:"uid"`
	CreateDate string      `json:"create_date"`
	GoodsInfos []GoodsInfo `json:"goods_infos"`
}

type StoreInfoReq struct {
	StoreId uint64 `form:"store_id"`
}

type StoreInfoResp struct {
	StoreInfo
}
