// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: genid.proto

package server

import (
	"context"

	"github.com/ac-dcz/lightRW/apps/genid/rpc/internal/logic"
	"github.com/ac-dcz/lightRW/apps/genid/rpc/internal/svc"
	"github.com/ac-dcz/lightRW/apps/genid/rpc/pb"
)

type GenIdServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGenIdServer
}

func NewGenIdServer(svcCtx *svc.ServiceContext) *GenIdServer {
	return &GenIdServer{
		svcCtx: svcCtx,
	}
}

func (s *GenIdServer) GetId(ctx context.Context, in *pb.GetIdReq) (*pb.GetIdResp, error) {
	l := logic.NewGetIdLogic(ctx, s.svcCtx)
	return l.GetId(in)
}
