// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: store.proto

package server

import (
	"context"

	"github.com/ac-dcz/lightRW/apps/store/rpc/internal/logic"
	"github.com/ac-dcz/lightRW/apps/store/rpc/internal/svc"
	"github.com/ac-dcz/lightRW/apps/store/rpc/pb"
)

type StoreServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedStoreServer
}

func NewStoreServer(svcCtx *svc.ServiceContext) *StoreServer {
	return &StoreServer{
		svcCtx: svcCtx,
	}
}

func (s *StoreServer) RegistryStore(ctx context.Context, in *pb.RegistryStoreReq) (*pb.RegistryStoreResp, error) {
	l := logic.NewRegistryStoreLogic(ctx, s.svcCtx)
	return l.RegistryStore(in)
}

func (s *StoreServer) GetStoreInfo(ctx context.Context, in *pb.StoreInfoReq) (*pb.StoreInfoResp, error) {
	l := logic.NewGetStoreInfoLogic(ctx, s.svcCtx)
	return l.GetStoreInfo(in)
}

func (s *StoreServer) AddGoods(ctx context.Context, in *pb.AddGoodsReq) (*pb.AddGoodsResp, error) {
	l := logic.NewAddGoodsLogic(ctx, s.svcCtx)
	return l.AddGoods(in)
}

func (s *StoreServer) GetGoodsStock(ctx context.Context, in *pb.GoodsStockReq) (*pb.GoodsStockResp, error) {
	l := logic.NewGetGoodsStockLogic(ctx, s.svcCtx)
	return l.GetGoodsStock(in)
}
