// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3
// Source: user.proto

package server

import (
	"context"

	"github.com/ac-dcz/lightRW/apps/user/rpc/internal/logic"
	"github.com/ac-dcz/lightRW/apps/user/rpc/internal/svc"
	"github.com/ac-dcz/lightRW/apps/user/rpc/pb"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserRpcServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) SignIn(ctx context.Context, in *pb.SignInReq) (*pb.SignInResp, error) {
	l := logic.NewSignInLogic(ctx, s.svcCtx)
	return l.SignIn(in)
}

func (s *UserRpcServer) SignUp(ctx context.Context, in *pb.SignUpReq) (*pb.SignUpResp, error) {
	l := logic.NewSignUpLogic(ctx, s.svcCtx)
	return l.SignUp(in)
}
