// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	"github.com/ac-dcz/lightRW/apps/store/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/add/goods",
				Handler: AddGoodsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/registry",
				Handler: RegistryStoreHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/api/v1/store"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/goods/stock",
				Handler: GetGoodsStockHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/info",
				Handler: GetStoreInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/store"),
	)
}
